version: '3.9'

services:
  postgres:
    image: postgres

    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DEV_DB_USER}
      - POSTGRES_PASSWORD=${DEV_DB_PASS}
      - POSTGRES_DB=${DEV_DB}
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

volumes:
  postgres: