ALTER TABLE orders 
    ADD COLUMN IF NOT EXISTS product_id UUID NOT NULL REFERENCES products(id), 
    ADD COLUMN IF NOT EXISTS quantity INTEGER NOT NULL CHECK (quantity > 0), 
    ADD COLUMN IF NOT EXISTS cost NUMERIC(1000, 2) NOT NULL CHECK(cost > 0);
